name: OneBlockPvPPlugin
version: '${project.version}'
main: me.ironblock.oneblockpvp.oneblockpvpplugin.OneBlockPvPPlugin
api-version: 1.16
authors: [ Iron__Block ]
description: BV1Fg411L7ji

commands:
  gameStart:
    description: "开始游戏!"
  autoStart:
    description: "是否自动开始游戏"